from __future__ import annotations

SCENARIOS = {'travel': {'template': 'flight_search', 'task_seed': 9101, 'prompt': 'Find the best flight from Mumbai to Delhi tomorrow for under ₹8,000. Prefer a nonstop flight when possible. Return the flight ID and price.', 'expected_answer': 'AI-218', 'fault_step': 1, 'fault_type': 'wrong_retrieval', 'fault_description': 'The flight-search tool returns stale/incomplete options and omits the best qualifying nonstop flight.', 'patch': {'target': 'output', 'value': {'flights': [{'id': 'AI-204', 'from': 'Mumbai', 'to': 'Delhi', 'price': 7600, 'stops': 1}, {'id': 'AI-218', 'from': 'Mumbai', 'to': 'Delhi', 'price': 7800, 'stops': 0}, {'id': '6E-611', 'from': 'Mumbai', 'to': 'Delhi', 'price': 9200, 'stops': 0}], 'source': 'replay_patch'}}}, 'support': {'template': 'damaged_order_replacement', 'task_seed': 9102, 'prompt': 'Order #4821 was delivered 10 days ago and arrived damaged. Check the replacement policy and decide whether the customer is eligible for a replacement.', 'expected_answer': 'Replacement not eligible', 'fault_step': 2, 'fault_type': 'wrong_retrieval', 'fault_description': 'The policy lookup returns an outdated 30-day replacement window instead of the current 7-day policy.', 'patch': {'target': 'output', 'value': {'window_days': 7, 'text': 'Damaged items can be replaced within 7 days of delivery.', 'source': 'replay_patch'}}}, 'expense': {'template': 'sales_growth', 'task_seed': 9103, 'prompt': 'Using the quarterly sales report, calculate the percentage increase in revenue from Q3 to Q4.', 'expected_answer': '25%', 'fault_step': 3, 'fault_type': 'corrupted_output', 'fault_description': 'The calculation stage produces an incorrect percentage despite having the correct Q3 and Q4 values.', 'patch': {'target': 'output', 'value': {'percentage_increase': 25, 'formula': '(150000-120000)/120000*100', 'source': 'replay_patch'}}}}


def get_scenario(name: str):
    if name not in SCENARIOS:
        raise ValueError(f"Unknown P1_TEST={name}. Available: {', '.join(SCENARIOS)}")
    return SCENARIOS[name]
